spring: 
 datasource: 
    url: ${MYSQL_CI_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
 jpa: 
    hibernate: 
      ddl-auto: create
    show-sql: true
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    
server:
  port: 8086

app:
  defaults:
    itemsperpage: 10